name: CI_no_jaxtrain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: "test on ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install Chirp and its dependencies, except jaxtrain dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg
          poetry install --without jaxtrain
      - name: Test with unittest
        run: poetry run python -m unittest discover -s chirp/tests -p "*test.py"
      - name: Test inference with unittest
        run: poetry run python -m unittest discover -s chirp/inference/tests -p "*test.py"
